export const cities  = ['Tirana','Durres'] ;
export const checkoutTypes  = ['Card Id'] ;
export const popularCitizenships = [
    'China',
    'India',
    'United States',
    'Indonesia',
    'Pakistan',
    'Brazil',
    'Nigeria',
    'Bangladesh',
    'Russia',
    'Mexico',
    'Japan',
    'Ethiopia',
    'Philippines',
    'Egypt',
    'Vietnam',
    'DR Congo',
    'Turkey',
    'Iran',
    'Germany',
    'Thailand',
    'United Kingdom',
    'France',
    'Italy',
    'South Africa',
    'Tanzania',
    'Myanmar',
    'South Korea',
    'Colombia',
    'Kenya',
    'Spain',
    'Argentina',
    'Algeria',
    'Ukraine',
    'Iraq',
    'Afghanistan',
    'Poland',
    'Canada',
    'Morocco',
    'Saudi Arabia',
    'Uzbekistan',
    'Malaysia',
    'Peru',
    'Venezuela',
    'Uganda',
    'Ghana',
    'Nepal',
    'Yemen',
    'North Korea',
    'Mozambique',
    'Taiwan',
    'Cameroon',
    'Côte d\'Ivoire',
    'Madagascar',
    'Australia',
    'Netherlands',
    'Chile',
    'Kazakhstan',
    'Malawi',
    'Ecuador',
    'Guatemala',
    'Syria',
    'Cambodia',
    'Senegal',
    'Chad',
    'Somalia',
    'Zimbabwe',
    'Guinea',
    'Rwanda',
    'Benin',
    'Burundi',
    'Tunisia',
    'Bolivia',
    'Belgium',
    'Haiti',
    'Cuba',
    'South Sudan',
    'Dominican Republic',
    'Czech Republic',
    'Greece',
    'Jordan',
    'Portugal',
    'Azerbaijan',
    'Sweden',
    'Honduras',
    'United Arab Emirates',
    'Hungary',
    'Belarus',
    'Tajikistan',
    'Austria',
    'Papua New Guinea',
    'Serbia',
    'Israel',
    'Switzerland',
    'Togo',
    'Sierra Leone',
    'Hong Kong',
    'Laos',
  ];